{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customers\",\"Order Details\",\"Orders\",\"Products\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-ZA",
    "cultures": [
      {
        "name": "en-ZA",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "eca8f53a-ddc7-4809-8a20-b44f10bcf798",
        "fromColumn": "OrderDate",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0c2e6591-7dc3-488c-a6ed-688f0ae5e910"
      },
      {
        "name": "06c13792-1e71-4c68-b61c-858b73e985fd",
        "fromColumn": "CustomerId",
        "fromTable": "Orders",
        "toColumn": "CustomerId",
        "toTable": "Customers"
      },
      {
        "name": "036caab2-0d88-43a8-b018-16ccbed5e31e",
        "fromColumn": "OrderId",
        "fromTable": "Order Details",
        "toColumn": "OrderId",
        "toTable": "Orders"
      },
      {
        "name": "8852ad73-c041-4527-ad90-5f26b65b4d14",
        "fromColumn": "ProductId",
        "fromTable": "Order Details",
        "toColumn": "ProductId",
        "toTable": "Products"
      }
    ],
    "sourceQueryCulture": "en-ZA",
    "tables": [
      {
        "name": "DateTableTemplate_2b7e48b4-5d86-42f9-9087-bb728d3c1cf9",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6099654c-927d-463c-8661-3e6c78097749",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "90a942c0-d5b7-4843-bc4f-37cd1e6b0e15",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "16e56887-4428-40e4-9eeb-0b1fcafd2d07",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3bb91255-85e7-4f6e-aecf-2386fcf4c473",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2b27dffc-6a7d-4baf-88d4-d71693d22c1f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3247533f-b220-441b-9eb5-8d02bb4b7610",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c7925043-50a5-4d02-a184-71a1bdd0b674",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fc66cac0-3dbc-4d47-b86b-c47f6fc55664",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d7a00180-19e1-40cc-9848-52b3fa7b931c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "94582fd3-35a7-47be-a5f3-32efe9c13828",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a4e7968b-cca8-4b7d-a396-6c57a517a490",
                "ordinal": 3
              }
            ],
            "lineageTag": "4bf6e067-5a1c-4b91-9c5e-88d127225230"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3b5500d7-860d-4ac2-bf69-64b708cd2920",
        "partitions": [
          {
            "name": "DateTableTemplate_2b7e48b4-5d86-42f9-9087-bb728d3c1cf9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Customers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd14d52b-f0b1-4dca-8f3c-160be4e7011c",
            "sourceColumn": "CustomerId",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffb8e02c-7aa6-40a2-9297-95e62529fbb3",
            "sourceColumn": "CustomerTitle",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffbdab94-b75a-42d5-a2c0-7f303aece9de",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "CellPhone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ff09f7e-5d78-4099-bc8b-e351f6d71bfb",
            "sourceColumn": "CellPhone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6205d952-07f6-41f9-acfc-e3fbe0d9d51c",
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac.sharepoint.com/sites/CMPG323/Shared%20Documents/CMPG323%202023/Projects/Project%205/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    Customers_Sheet = Source{[Item=\"Customers\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Customers_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerId\", Int64.Type}, {\"CustomerTitle\", type text}, {\"Name\", type text}, {\"CellPhone\", Int64.Type}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"CustomerId\"}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Blank Rows\", {\"CustomerId\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Errors\",{{\"CellPhone\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Order Details",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OrderDetailsID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79f899e8-8369-4de0-b761-608e37a4c6c6",
            "sourceColumn": "OrderDetailsID",
            "summarizeBy": "count"
          },
          {
            "name": "OrderId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9b3ad1ff-a4cb-412b-ac49-9201d26d25ab",
            "sourceColumn": "OrderId",
            "summarizeBy": "none"
          },
          {
            "name": "ProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "344c0265-c336-4ed6-96b6-2c177682a34a",
            "sourceColumn": "ProductId",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e86d0784-fdbf-4430-a50f-1a955f0a2176",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4dbe6e72-112e-435f-bea3-3bb1cabf858d",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "expression": "'Order Details'[Quantity] * (1- 'Order Details'[Discount]) * RELATED(Products[Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "46eaa8fe-a396-4c76-847e-793b2c38364d",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "4a6c5556-41b9-4374-919d-749c8d25a708",
        "partitions": [
          {
            "name": "Order Details",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac.sharepoint.com/sites/CMPG323/Shared%20Documents/CMPG323%202023/Projects/Project%205/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    #\"Order Details_Sheet\" = Source{[Item=\"Order Details\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Order Details_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderDetailsID\", Int64.Type}, {\"OrderId\", Int64.Type}, {\"ProductId\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"Discount\", type number}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"OrderDetailsID\"}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Blank Rows\", {\"OrderDetailsID\"}),",
                "    #\"Removed Alternate Rows\" = Table.AlternateRows(#\"Removed Errors\",10,2,38),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Alternate Rows\", \"Sales\", each [Quantity]*(1-[Discount]) * (Products[Price]) ),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"Sales\"}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Removed Columns\", \"Sales\", each [Quantity]*(1-[Discount])),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Custom1\",{\"Sales\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OrderId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7fac77e7-2241-41cf-889b-dfbc04178787",
            "sourceColumn": "OrderId",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d5319f0e-b3cd-460e-af3f-b616735dcd1d",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0c2e6591-7dc3-488c-a6ed-688f0ae5e910"
                },
                "isDefault": true,
                "relationship": "eca8f53a-ddc7-4809-8a20-b44f10bcf798"
              }
            ]
          },
          {
            "name": "CustomerId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb8baa17-3a8c-4cae-8792-3040dfdcad99",
            "sourceColumn": "CustomerId",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69aa99bd-bcb8-4261-bd5f-88063c8dac79",
            "sourceColumn": "DeliveryAddress",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ef972238-d537-4bb2-9d16-b4eadce7b1b4",
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac.sharepoint.com/sites/CMPG323/Shared%20Documents/CMPG323%202023/Projects/Project%205/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderId\", Int64.Type}, {\"OrderDate\", type any}, {\"CustomerId\", Int64.Type}, {\"DeliveryAddress\", type text}, {\"Column5\", Int64.Type}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"OrderId\"}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Blank Rows\", {\"OrderId\"}),",
                "    #\"Removed Alternate Rows\" = Table.AlternateRows(#\"Removed Errors\",3,1,14),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Alternate Rows\", \"Custom\", each if [OrderId] >= 100216 then #date(2023, 3, 1) else if [OrderId] >= 100209 then #date(2023, 7, 13) else if [OrderId] >= 100202 then #date(2023, 6, 15) else if [OrderId] >= 100160 then #date(2023, 7, 18) else if [OrderId] >= 100153 then #date(2023, 6, 10) else if [OrderId] >= 100146 then #date(2023, 5, 5) else if [OrderId] >= 100111 then #date(2023, 7, 25) else if [OrderId] >= 100097 then \"2023/08/01\" else if [OrderId] >= 100090 then #date(2023, 2, 10) else if [OrderId] >= 100069 then #date(2023, 5, 8) else if [OrderId] >= 100055 then #date(2023, 7, 3) else if [OrderId] >= 100048 then #date(2023, 6, 25) else #date(2023, 2, 2), type any),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"OrderId\", \"Custom\", \"OrderDate\", \"CustomerId\", \"DeliveryAddress\", \"Column5\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"OrderDate\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"OrderDate\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"OrderDate\", type date}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"Column5\"}),",
                "    #\"Removed Alternate Rows1\" = Table.AlternateRows(#\"Removed Columns1\",2,1,13)",
                "in",
                "    #\"Removed Alternate Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0c2e6591-7dc3-488c-a6ed-688f0ae5e910",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0e522554-4526-4b77-bfc7-6e62943326c1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5777a39d-b8f4-4044-917e-74c391202c61",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c1205fa7-89bb-4e3b-ac0b-d0954f76c4e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "23ff0e7b-1a59-474e-8286-065277ffe26c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0e32540f-8e79-4622-813d-7f3a714a72fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7fd2285c-2226-4c33-bdb4-7ccfc44d091e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "42415057-2550-492a-a408-0d4c06d108f5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "501cdb1c-1141-4ea4-bd09-c209c0ac037c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2fad036c-586e-4701-ab50-6e8a0f9caea2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "508e68b1-e47a-49c7-9fd8-53c50e8dd915",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "53929f5b-22f5-42a7-b8e3-624a790a6726",
                "ordinal": 3
              }
            ],
            "lineageTag": "573712be-d5b2-43d3-a480-b4ee002d4260"
          }
        ],
        "isHidden": true,
        "lineageTag": "a0df313e-1ab1-4317-b0c5-02e6b7bbbccc",
        "partitions": [
          {
            "name": "LocalDateTable_0c2e6591-7dc3-488c-a6ed-688f0ae5e910",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[OrderDate])), 1, 1), Date(Year(MAX('Orders'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30c82fe4-b0ce-41ab-9fdd-4fc58b84f6e0",
            "sourceColumn": "ProductId",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56cec265-cc66-4bbc-b06c-a35c9f63d621",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5140ade1-cf8b-4f21-9109-d1a4a2385520",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "UnitsInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2703933d-d5af-4d26-ad00-a1682690d656",
            "sourceColumn": "UnitsInStock",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "bff90b66-5982-47cf-897c-81e42a87b7d7",
            "sourceColumn": "Price",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "60d259bf-475b-4fb4-98fc-53bcbc51f69b",
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac.sharepoint.com/sites/CMPG323/Shared%20Documents/CMPG323%202023/Projects/Project%205/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    Products_Sheet = Source{[Item=\"Products\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Products_Sheet,{{\"Column1\", type any}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type any}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"Column1\"}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Blank Rows\", {\"Column1\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Errors\",{{\"Column1\", \"ProductId\"}, {\"Column2\", \"ProductName\"}, {\"Column3\", \"Category\"}, {\"Column4\", \"UnitsInStock\"}}),",
                "    #\"Removed Alternate Rows\" = Table.AlternateRows(#\"Renamed Columns\",16,1,39),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Alternate Rows\",{{\"UnitsInStock\", Int64.Type}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type1\", \"Price\", each if [ProductId] >= 10004667 then \"$300\" else if [ProductId] >= 10004495 then \"$250\" else if [ProductId] >= 10004086 then \"$50\" else if [ProductId] >= 10004015 then \"$200\" else if [ProductId] >= 10003715 then \"$100\" else if [ProductId] >= 10003623 then \"$40\" else if [ProductId] >= 10003072 then \"$10\" else if [ProductId] >= 10003061 then \"$200\" else if [ProductId] >= 10003012 then \"$100\" else if [ProductId] >= 10002968 then \"$200\" else if [ProductId] >= 10002885 then \"$15\" else if [ProductId] >= 10002713 then \"$10\" else if [ProductId] >= 10002647 then \"$40\" else if [ProductId] >= 10002563 then \"$150\" else if [ProductId] >= 10002475 then \"$10\" else if [ProductId] >= 10002310 then \"$100\" else if [ProductId] >= 10002012 then \"$10\" else if [ProductId] >= 10001979 then \"$40\" else if [ProductId] >= 10001772 then \"$15\" else if [ProductId] >= 10001622 then \"$10\" else if [ProductId] >= 10001606 then \"$50\" else if [ProductId] >= 10001597 then \"$20\" else if [ProductId] >= 10001509 then \"$10\" else if [ProductId] >= 10001473 then \"$20\" else if [ProductId] >= 10001469 then \"$30\" else if [ProductId] >= 10001465 then \"$20\" else if [ProductId] >= 10001215 then \"$250\" else if [ProductId] >= 10001154 then \"$50\" else if [ProductId] >= 10000807 then \"$10\" else if [ProductId] >= 10000788 then \"$300\" else if [ProductId] >= 10000615 then \"$20\" else if [ProductId] >= 10000418 then \"$200\" else if [ProductId] >= 10000343 then \"$10\" else if [ProductId] >= 10000304 then \"$5\" else if [ProductId] >= 10000241 then \"$20\" else \"$70\", type text),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Added Conditional Column\",\"$\",\"\",Replacer.ReplaceText,{\"Price\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Price\", Currency.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}